spring.application.name=vbs

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://vbs_db_aifo_user:CoEaVVOXIomzkuiMS2rShZMTxOZSzGjS@dpg-d6sp0t95pdvs73dvpjt0-a.singapore-postgres.render.com/vbs_db_aifo
spring.datasource.username=vbs_db_aifo_user
spring.datasource.password=CoEaVVOXIomzkuiMS2rShZMTxOZSzGjS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# DIALECT
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER
# ===============================
server.port=${PORT:8081}